config/routes.rb
Rails.application.routes.draw do
  root :to=> 'hostel_operation#index'
  get 'owner/all_request'
  get 'leave/show_owner'
  get 'room_management/get_all_room'
  resources :hostel_operation
  post 'hostel_operation/check_auth'
  resources :room_management
  resources :owner
  resources :student do
    resources :leave
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave.rb
class Leave < ApplicationRecord
    belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user
    self.primary_key='room_no'
    validates :room_no, uniqueness:true
    validates :capacity,numericality:{only_integer:true}
    validates :room_no,:capacity, presence: true

    before_create :add_vacancy

    def add_vacancy
        self.vacancy=self.capacity
    end
end

app/models/user.rb
class User < ApplicationRecord  
    has_many :leave
    validates :username,uniqueness:true

    before_create :add_role

    def add_role
        if self.role==nil
            self.role='student'          
        else
            self.room_no='0'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hostel_operation_controller.rb
class HostelOperationController < ApplicationController
    
    def index
        @user=User.new
    end

    def new
        @user=User.new
    end
  
    def create
       @user=User.new(get_paramas)
       @user.save
    
       index
       render 'index'
    end

    def edit
        @user=User.find_by_id(params[:id]);
    end

    def update
        @user=User.find(params[:id])
        @user.status=true
        @user.update(get_paramas)
        session[:HostelId]=@user.id
        redirect_to student_index_path
    end

    def check_auth
        @username=params[:user][:username]
        @password=params[:user][:password]
        @role=params[:user][:role]
        @user=User.where(username:@username,password:@password,role:@role)
        if @user.blank?
            index()
            render 'index'
        else
            if @user[0].role=='student'
                if @user[0].status
                    session[:HostelId]=@user[0].id
                    redirect_to student_index_path
                else
                    redirect_to edit_hostel_operation_path(@user[0].id)
                    
                end
                
            else
                redirect_to owner_index_path
            end
        end
    end

    def get_paramas
        params.require(:user).permit(:firstname,:lastname,:email,:phoneno,:username,:password,:role,:status,:room_no)
    end
end

app/controllers/leave_controller.rb
class LeaveController < ApplicationController

    def index
    end

    def new
        @user=User.find(session[:HostelId])
        @leave=Leave.new
    end

    def create
        if session[:HostelId]!=nil
            @leave=Leave.new(get_params)
            @leave.user_id=session[:HostelId]
            if @leave.save
                redirect_to student_leave_index_path(session[:HostelId])
            else
                redirect_to student_leave_index_path(session[:HostelId])
            end
        else
            puts 'Session Khatam'
            redirect_to student_leave_index_path(session[:HostelId])
        end
    end

    def show
        if session[:HostelId]!=nil
            @user=User.find(params[:student_id])
            @leaves=@user.leave
        end        

             
    end

    def show_owner 
        if session[:HostelId]!=nil
            @all_leave=Leave.where(status:'Pending')
            
        end        
    end

    def update
        if params[:flag]=='approve'
            @leave=Leave.find(params[:id])
            @leave.status='Approved'
            @leave.save
        elsif params[:flag]=='reject'
            @leave=Leave.find(params[:id])
            @leave.status='Rejected'
            @leave.save
        end
        redirect_to leave_show_owner_path
    end
    

    def get_params
        params.require(:leave).permit(:user_id,:reason,:subject,:date_to,:date_from,:status)
    end
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController

    def index
        @owner=User.find_by(role:'owner')
        @total_rooms=Room.all.size
        @total_capacity=Room.sum('capacity');
        @total_vacancy=Room.sum('vacancy');
    end

    def new
        @user=User.new
    end

    def create    
        @user=User.new(get_paramas)
        @room=Room.find_by(room_no:@user.room_no)
        @room.vacancy=@room.vacancy-1
        if @room==nil
            flash[:notice]='Room does not exist'
        elsif @room.vacancy<0
            flash[:notice]='Not enough space in this room'
            redirect_to new_owner_path
        elsif @user.save && @room.save
            index
            render 'index'
        else
            render 'new'
        end
    end
    
    def get_paramas
        params.require(:user).permit(:firstname,:lastname,:email,:phoneno,:username,:password,:role,:hostel_id,:room_no)
    end

    def all_request  
        @no_of_leave=Leave.where(status:'Pending').size
    end
end

app/controllers/room_management_controller.rb
class RoomManagementController < ApplicationController

    def index    
    end

    def show
        @users=User.where(room_no:params[:id])
    end
    
    def get_all_room
        @rooms=Room.all
    end

    def new
        @room = Room.new;
    end

    def create
        @room=Room.new(get_params)
    
        if @room.save
            render 'index'
        else
            render 'new'
        end
    end

    def get_params
        params.require(:room).permit(:room_no,:capacity,:vacancy)
    end
    
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    def index
        @user=User.find(session[:HostelId])
        @room_members=User.where(room_no:@user.room_no)
        @total_rooms=Room.all.size
        @total_capacity=Room.sum('capacity');
        @total_vacancy=Room.sum('vacancy');
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hostel_operation_helper.rb
module HostelOperationHelper
end

app/helpers/leave_helper.rb
module LeaveHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/room_management_helper.rb
module RoomManagementHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/hostel_operation/Main_page.html.erb
Successfull

app/views/hostel_operation/edit.html.erb
<div class="container">

	<div class="container text-center">
		<h2 class=" pt-3 pb-2"><b>Welcome to <a style="color:  #FF5C20">Hostel</a> management System</b></h2>
		<hr class="w-100 mx-auto">
	</div>

	 <div class="row mt-2">
		<div class="col-12">
			<h2><b>Sign Up</b></h2>
			<%=form_for @user,url:hostel_operation_path,method:'patch' do |f|%>
					<div class="row mt-4">
					    <div class="col">
					      <label>First Name :</label><br>
						      <%=f.text_field :firstname, class:'form-control'%>
					    </div>
                        <div class="col">
					      <label>Last Name :</label><br>
						      <%=f.text_field :lastname, class:'form-control'%>
					    </div>
					</div>

                    <div class="row mt-4">
					    <div class="col">
					      <label>Rloe :</label><br>
						      <%=f.text_field :role, class:'form-control',readonly:true%>
					    </div>
					</div>

                    <div class="row mt-2">
					    <div class="col">
					      <label>Email Id :</label>
					      <%=f.text_field :email, class:'form-control'%>
					    </div>
					  </div>

                      <div class="row mt-2">
					    <div class="col">
					      <label>Phone No :</label>
					      <%=f.text_field :phoneno, class:'form-control'%>
					    </div>
						<div class="col",display=<%=@visable%>>
					      <label>Room No :</label>
					      <%=f.text_field :room_no, class:'form-control',readonly:true%>
					    </div>
					  </div>

					  <div class="row mt-2">
					    <div class="col">
					      <label>UserName/Hostel Id :</label>
					      <%=f.text_field :username, class:'form-control',readonly:true%>
					    </div>
					  </div>
					  <div class="row mt-2">
					    <div class="col">
					      <label>Password :</label>
                          <%=f.password_field :password, class:'form-control'%>
					    </div>
					  </div>
					<%=f.submit 'Sign Up'%>   
                <%end%>
		</div>
	</div>
</div>

app/views/hostel_operation/index.html.erb
<div class="container">

	<div class="container text-center">
		<h2 class=" pt-3 pb-2"><b>Welcome to <a style="color:  #FF5C20">Hostel</a> management System</b></h2>
		<hr class="w-100 mx-auto">
	</div>

	 <div class="row mt-2">
		<div class="col-sm-6 col-12">
			<h2><b>Log In Form Here</b></h2>
			<%=form_for @user,url:hostel_operation_check_auth_path,method:'post' do |f|%>
					<div class="row mt-4">
					    <div class="col">
					      <label>Enter Your Role :</label><br>	
							<%=f.select :role,['owner','student'],{},{class:'form-control'}%>
					    </div>
					  </div>
		
					  <div class="row mt-2">
					    <div class="col">
					      <label>UserName/Hostel Id :</label>
					      <%=f.text_field :username, class:'form-control'%>
					    </div>
					  </div>
					  <div class="row mt-2">
					    <div class="col">
					      <label>Password :</label>
                          <%=f.password_field :password, class:'form-control'%>
					      
					    </div>
					  </div>
					<%=f.submit 'Log In'%>   
					
                    <%= link_to 'Create New Account', new_hostel_operation_path%>
					
				<a href="forgetpassword.html">Forget Password?</a>
                <%end%>
		</div>

		<div class="col-lg-6 col-md-6 col-12" style="border:2px solid orange ; border-radius: 5%">
			<div class="ml-5 mt-2">
			<h2 class="pt-5"><b>About this platform</b></h2><br>
			<p>In current scenario owner has to keep the record of all hosteller on paper which is very difficult to manage, search, update etc. If owner want some data of perticular hosteller then it would be very difficult for him/her to find out data and it is also time consuming.</p>
			<p>So this is the platform where owner can store each and every information of hosteller as well as about the hostel with few clicks. This system is designed in favour of the database management which helps them to save rent related data, food management, vacancies of rooms, guest night stay data etc.</p>
			</div>
		</div>

	</div>
</div>

app/views/hostel_operation/new.html.erb
<div class="container">

	<div class="container text-center">
		<h2 class=" pt-3 pb-2"><b>Welcome to <a style="color:  #FF5C20">Hostel</a> management System</b></h2>
		<hr class="w-100 mx-auto">
	</div>

	 <div class="row mt-2">
		<div class="col-12">
			<h2><b>Sign Up</b></h2>
			<%=form_for @user,url:hostel_operation_index_path,method:'post' do |f|%>
					<div class="row mt-4">
					    <div class="col">
					      <label>First Name :</label><br>
						      <%=f.text_field :firstname, class:'form-control'%>
					    </div>
                        <div class="col">
					      <label>Last Name :</label><br>
						      <%=f.text_field :lastname, class:'form-control'%>
					    </div>
					</div>

                    <div class="row mt-4">
					    <div class="col">
					      <label>Role :</label><br>
							  <%=f.select :role,['owner','student'],{},{class:'form-control'}%>
					    </div>
					</div>

                    <div class="row mt-2">
					    <div class="col">
					      <label>Email Id :</label>
					      <%=f.text_field :email, class:'form-control'%>
					    </div>
					  </div>

                      <div class="row mt-2">
					    <div class="col">
					      <label>Phone No :</label>
					      <%=f.text_field :phoneno, class:'form-control'%>
					    </div>
						<div class="col",display=<%=@visable%>>
					      <label>Room No :</label>
					      <%=f.text_field :room_no, class:'form-control',readonly:true%>
					    </div>
					  </div>

					  <div class="row mt-2">
					    <div class="col">
					      <label>UserName/Hostel Id :</label>
					      <%=f.text_field :username, class:'form-control',readonly:@visible%>
                          <!--<f:input type="text" class="form-control" placeholder="Enter UserName" path="username"  cssStyle="width:70%"/>-->
					    </div>
					  </div>
					  <div class="row mt-2">
					    <div class="col">
					      <label>Password :</label>
                          <%=f.password_field :password, class:'form-control'%>
					      <!--<f:input type="Password" class="form-control" placeholder="Enter Password" path="password"  cssStyle="width:70%"/>-->
					    </div>
					  </div>
					<%=f.submit 'Sign Up'%>   
					<!--<button type="submit" class="btn mt-3 text-white" style="background-color:#FF5C20 ; width:25%">Log In</button>-->
                <%end%>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <title>HDMS</title>
  </head>
  <body>
  <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/leave/index.html.erb
<%= render 'owner/header' %>
<%= render 'student/menu' %>
jyqefhdsiujkg
<div class="container">
	<div class="row pl-5" style="margin-top:10%;">
		

		<div class="col-sm-6 col-6 pl-5" >
			 	 <div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='far fa-dizzy mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col text-center"><h4 class="ml-3 mt-1"><b><%=link_to 'Leave Application Apply',new_student_leave_path(session[:HostelId])%></b></h4>
				  	</div>
				  </div>
			</div>	 
		</div>
		<div class="col-sm-6 col-6 pl-5" style="border:0px solid black">
			<div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
					  <center><i class='fas fa-question-circle mt-2' style='font-size:100px;color:#FC3900'></i></center>
					  <hr>
					  <div class="row" style="height:auto;width:100%;border:0px solid black">
					  	<div class="col text-center"><h4 class="ml-3 mt-1"><b><%=link_to 'Leave Application Status',student_leave_path(session[:HostelId],0)%></b></h4>
					  	</div>
					  </div>
				</div>
	   </div>	
	</div>
</div>
</div>

app/views/leave/show_owner.html.erb
<%= render 'owner/header' %>
<%= render 'owner/menu' %>
<div style="height:auto;width:60%;margin-top:5%;margin-left:30%;border:2px solid orange;border-radius:5%" class="bg-light">
	   			<h2 class="pt-4 text-center "><b>Leave Applications</b></h2>
	   			<hr>
		   			<table class="table table-stripped table-hover table-bordered">
		   	<tr class="table-danger">		
		   	<td><b>No.</b></td>
			<td><b>Hostel_id</b></td>
			<td><b>Date From</b></td>
			<td><b>Date To</b></td>
			<td><b>Reason</b></td>
			<td><b>Approve Requests</b></td>
			<td><b>Reject Requests</b></td>
			</tr>
			
			<%i=0%>
			 <%@all_leave.each do |leave_request|%>
                <tr>	
                <td><b><%=i=i+1%></b></td>
                <td><b><%=leave_request.user.username%></b></td>
                <td><b><%=leave_request.date_from%></b></td>
                <td><b><%=leave_request.date_to%></b></td>
                <td><b><%=leave_request.reason%></b></td>
                <td><center><b><%=button_to 'Approve',student_leave_path(leave_request.user,leave_request,flag:'approve'),class:"btn btn-success",method:'put'%></b></center></td>
                <td><center><b><%=button_to 'Reject',student_leave_path(leave_request.user,leave_request,flag:'reject'),class:"btn btn-danger",method:'put'%></b></center></td>
                </tr>
            <%end%>
				</table>
				
	   		</div>
</div>

app/views/owner/_header.html.erb
<nav class="navbar navbar-expand-sm text-white navbar-dark" style="border:2px solid black;background-color: #FF5C20;font-family: Montserrat, sans-serif;">  
    <img src="logo.png" alt="logo" style="width:7%;"> 
  	<h1 style="margin-left:20%"><b>Hostel Management System</b></h1>
</nav>

app/views/owner/_menu.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
<div>
	<table class="table table-hover table-striped" style="width:20%;background-color:#f4511e;float:left">
		<thead class="thead-dark">
			<tr>
				<th >Dashboard<i class="fa fa-dashboard  float-right" style="font-size:24px;color:white"></i>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="text-warning"><a href="#" class="link"><div style="height:100%;width:100%;"><i class='fas fa-home' style='font-size:35px;color:white;'></i><x class="ml-4" style="color:black"><b><%= link_to 'Home', owner_index_path,class:"link text-white" %></b></x></div></a>
				</td>
     		</tr>
      		<tr>
    			<th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fas fa-user-graduate' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> View Student Info.</b></x></div></a>
    			</th>
    		</tr>
    		<tr>
  			    <th ><div style="height:100%;width:100%"><i class='fas fa-user-edit' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b><%= link_to 'Request', owner_all_request_path,class:"link text-white" %></b></x></div>
  			    </th>
  			</tr>
     		<tr>
    			<th><div style="height:100%;width:100%"><i class='fas fa-id-card' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><%= link_to 'Generate Hostel Id', new_owner_path ,class:"link text-white"%></x></div>
					
				</th>
    		</tr>
    		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fas fa-th-list' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black"><%= link_to 'Room Management', room_management_index_path ,class:"link text-white"%></x></div>
    			</th>
    		</tr>
     		<tr>
  			    <th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-bar-chart' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black"><b>Analysis</b></x></div></a>
  			    </th>
    		</tr>
    		<tr>
    			<th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-address-card-o' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b> Attendance</b></x></div></a>
    			</th>
    		</tr>
     		<tr>
    			<th><a href="#" class="link text-white "><div style="height:100%;width:100%"><i class='fa fa-exclamation-circle' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b> View Complains</b></x></div></a></th>
    		</tr>
    		<tr>
		     	<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-commenting' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b>Message for student</b></x></div></a></th>
		     </tr>
    		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fa fa-sign-out' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black"><%= link_to 'Logout', hostel_operation_index_path ,class:"link text-white"%>
    			</th>
   			 </tr>
		</tbody>
</table>
</div>

app/views/room_management/get_all_room.html.erb
<%= render 'owner/header' %>
<%= render 'owner/menu' %>
<%i=1%>
<div style="height:auto;width:60%;margin-top:5%;margin-left:30%;border:2px solid orange;border-radius:5%" class="bg-light">
	   			<h2 class="pt-4 text-center "><b>Room Information</b></h2>
	   			<hr>
		   			<table class="table table-stripped table-hover table-bordered">
		   	<tr class="table-danger">		
		   	<td><b>No.</b></td>
			<td><b>Room No</b></td>
			<td><b>Capacity Of Room</b></td>
			<td><b>Current Member In Room</b></td>
			<td><b>View Room</b></td>
			</tr>
			
			
			 <%@rooms.each do |room|%>	
			<tr>	
		   	<td><b><%=i%></b></td>
			<td><b><%=room.room_no%></b></td>
			<td><b><%=room.capacity%></b></td>
			<td><b><%=room.capacity-room.vacancy%></b></td>
			<td><center><b><%=link_to 'View Room', room_management_path(room.id)%></b></center></td>
			</tr><%i=i+1%>
			<%end%>	   			
		   			</table>
	   		</div>
</div>

app/views/room_management/index.html.erb
<%= render 'owner/header' %>
<%= render 'owner/menu' %>
<div class="container">
	<div class="row mt-3">
	
			<div class="col-lg-6 col-md-6 col-12" style="border:0px solid black">
			 <div class="card mt-5 ml-5 " style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fa fa-info-circle mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><%= link_to 'Room Information',room_management_get_all_room_path,class:"link text-black"%></b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b>4</b></h4>
				  	</div>
				  </div>
			</div>
			<a href="deallocaetroom.html"><div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
					<center><i class='fas fa-exchange-alt mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b>De-allocate<br>Room</b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b>3</b></h4>
				  	</div>
				  </div>				 
			</div> </a>
		</div>
		<div class="col-lg-6 col-md-6 col-12" style="border:0px solid black">
			 <div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa-plus mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b><%= link_to 'Add Room',new_room_management_path,class:"link text-black"%></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b>5</b></h4>
				  	</div>
				  </div>
			</div>
			<a href="loadremoveroom.html"><div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa fa-times mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b>Remove<br> Room</b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b>23</b></h4>
				  	</div>
				  </div>
			</div></a>
		</div>
	</div>
</div>
</div>

app/views/student/_menu.html.erb
<table class="table table-hover table-striped" style="width:20%;background-color:#f4511e;float:left">
		<thead class="thead-dark">
			<tr>
				<th >Dashboard<i class="fa fa-dashboard  float-right" style="font-size:24px;color:white"></i>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th class="text-warning"><a href="#" class="link text-white"><div style="height:100%;width:100%;"><i class='fas fa-home' style='font-size:35px;color:white;'></i><x class="ml-4" style="color:black"><b>Home</b></x></div></a>
				</th>
     		</tr>
     		<tr>
				<th class="text-warning"><a href="#" class="link text-white"><div style="height:100%;width:100%;"><i class='fas fa-upload' style='font-size:35px;color:white;'></i><x class="ml-4" style="color:black"><b>Fee Receipt</b></x></div></a>
				</th>
     		</tr>
      		<tr>
    			<th><div style="height:100%;width:100%"><i class='fa fa-building' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> <%= link_to 'Leave Application', student_leave_index_path(session[:HostelId]) ,class:"link text-white"%></b></x></div>
    			</th>
    		</tr>
    		 <tr>
  			    <th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fas fa-bed' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b>Guests Stay Request</b></x></div></a>
  			    </th>
  			</tr> 
  			
     		<tr>
    			<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-cutlery' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> Food Coupon Apply</b></x> </div></a>
    			</th>
    		</tr>
    		
    		<tr>
    			<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fas fa-exclamation-circle' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> Complain</b></x></div></a>
    			</th>
    		</tr>
    		
    		<tr>
    			<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-users' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b>Visitor</b></x></div></a>
    			</th>
    		</tr>
     		
     		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fa fa-sign-out' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b><%= link_to 'Logout', hostel_operation_index_path ,class:"link text-white"%></b></x></div>
    			</th>
    		</tr>
    		
		</tbody>

</table>